# permissions for end users to edit mysqlinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlinstance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crdproject
    app.kubernetes.io/part-of: crdproject
    app.kubernetes.io/managed-by: kustomize
  name: mysqlinstance-editor-role
rules:
- apiGroups:
  - mysql.my.test.domain
  resources:
  - mysqlinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.my.test.domain
  resources:
  - mysqlinstances/status
  verbs:
  - get
