# permissions for end users to view mysqlinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlinstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crdproject
    app.kubernetes.io/part-of: crdproject
    app.kubernetes.io/managed-by: kustomize
  name: mysqlinstance-viewer-role
rules:
- apiGroups:
  - mysql.my.test.domain
  resources:
  - mysqlinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.my.test.domain
  resources:
  - mysqlinstances/status
  verbs:
  - get
